const uczniowie = [
    {
        sala: 41,
        imie: "Izabela",
        nazwisko: "Łączkowska",
        przedmiot: "J. Angielski",
        opis: "Pilnie się uczyć, mieć zeszyt i książkę, być uprzejmym.",
    },
    {
        sala: 42,
        imie: "Ilona",
        nazwisko: "Łukasik",
        przedmiot: "J. Angielski",
        opis: "Nie korzystać z telefonu, bądź miły i uprzejmy, pracuj systematycznie na lekcji, nie niszcz sali, nie śpij na lekcji.",
    },
    {
        sala: 43,
        imie: "Anna",
        nazwisko: "Nadolska",
        przedmiot: "J. Angielski",
        opis: "Nie rozmawiać na lekcji, pilnie się uczyć, nie ściągać.",
    },
    {
        sala: 44,
        imie: "Klaudia",
        nazwisko: "Wyrzyk",
        przedmiot: "J. Angielski",
        opis: "--",
    },
    {
        sala: 47,
        imie: "Ewa",
        nazwisko: "Machnio",
        przedmiot: "J. Angielski",
        opis: "Nie robić sobie zaległości.",
    },
    {
        sala: 52,
        imie: "Anna",
        nazwisko: "Bądkowska",
        przedmiot: "J. Niemiecki",
        opis: "Polubić niemiecki, interesować się tematem.",
    },
    {
        sala: 58,
        imie: "Adam",
        nazwisko: "Bojanowski",
        przedmiot: "PSO, PSK, rysunek techniczny",
        opis: "Uczyć się, pracować.",
    },
    {
        sala: 59,
        imie: "Dagmara",
        nazwisko: "Sobkowiak",
        przedmiot: "J. Niemiecki",
        opis: "Nie gadać, chować telefony i nie mówić 'du hast'.",
    },
    {
        sala: 110,
        imie: "Krzysztof",
        nazwisko: "Wilkowski",
        przedmiot: "Historia, WOS, J. Angielski",
        opis: "Zmieniać buty, mieć wszystkie oceny, prowadzić zeszyt z historii.",
    },
    {
        sala: 112,
        imie: "Piotr",
        nazwisko: "Kopka",
        przedmiot: "Historia, WOS",
        opis: "Dbać o frekwencję i uczyć się.",
    },
    {
        sala: 115,
        imie: "Dorota",
        nazwisko: "Strupiechowska",
        przedmiot: "WIAI, Informatyka",
        opis: "Przestrzegać regulaminu, nie pić, nie jeść, regularnie się uczyć.",
    },
    {
        sala: 119,
        imie: "Henryk",
        nazwisko: "Giergielewicz",
        przedmiot: "Geografia, LSK",
        opis: "Uczyć się.",
    },
    {
        sala: 121,
        imie: "Ryszard",
        nazwisko: "Filipowicz",
        przedmiot: "EDB",
        opis: "Żeby się uczyli, mieć podręcznik.",
    },
    {
        sala: 135,
        imie: null,
        nazwisko: null,
        przedmiot: null,
        opis: "Nauczyciel nie współpracował.",
    },
    {
        sala: 136,
        imie: "Izabella",
        nazwisko: "Czerwiec",
        przedmiot: "Matematyka",
        opis: "Pracować systematycznie.",
    },
    {
        sala: 137,
        imie: "Barbara",
        nazwisko: "Tumanowicz",
        przedmiot: "Matematyka",
        opis: "Uczyć się, w razie problemu nie bać się i pytać.",
    },
    {
        sala: 139,
        imie: "Elżbieta",
        nazwisko: "Wygnalska",
        przedmiot: "Matematyka",
        opis: "Uważać na lekcjach oraz pracować.",
    },
    {
        sala: 142,
        imie: "Krzysztof",
        nazwisko: "Kopiec",
        przedmiot: "Podstawy przedsiębiorczości",
        opis: "Pracować zgodnie z zasadami, prowadzić zeszyt, być przygotowanym do lekcji i przychodzić z dobrym nastawieniem, nie spać na lekcji.",
    },
    {
        sala: 149,
        imie: "Marcin",
        nazwisko: "Marczewski",
        przedmiot: "Matematyka, pracownia elektroniczna, systemy transmisji danych",
        opis: "Uczyć się, regularnie chodzić na lekcje, nie robić sobie zaległości.",
    },
    {
        sala: 150,
        imie: "Krzysztof",
        nazwisko: "Mróz",
        przedmiot: "Systemy operacyjne, sieci rozległe",
        opis: "Samokształcenie jest najważniejsze, nadążać za technologią.",
    },
    {
        sala: 212,
        imie: "Jolanta",
        nazwisko: "Wilkowska",
        przedmiot: ["Informatyka", "Fizyka"],
        opis: "--",
    },
    {
        sala: 213,
        imie: "Grzegorz",
        nazwisko: "Wyszomirski",
        przedmiot: ["PA", "PAM"],
        opis: "Pracować regularnie, zastanowić się, czy na pewno się to lubi.",
    },
    {
        sala: 215,
        imie: "Marta",
        nazwisko: "Grzeszczak",
        przedmiot: ["Informatyka", "PAIPO", "PO", "SBD", "PBD"],
        opis: "Systematyczna nauka (nie ma przelewek).",
    },
    {
        sala: 217,
        imie: "Grzegorz",
        nazwisko: "Kosmala",
        przedmiot: ["PSO", "PUTK", "PSK", "Informatyka"],
        opis: "Być samodzielnym, mieć pasję w kierunku.",
    },
    {
        sala: 219,
        imie: "Tomasz",
        nazwisko: "Dudkowski",
        przedmiot: ["Informatyka", "PSI", "Rysunek Techniczny", "WIAI"],
        opis: 'Zapamiętać loginy do EduWarszawy i domeny szkolnej, nauczyć się pisać "tczionka".',
    },
    {
        sala: 221,
        imie: "Małgorzata",
        nazwisko: "Rosińska",
        przedmiot: ["PRAI", "PSI", "PAI"],
        opis: "Pracować sumiennie i nie ściągać z internetu, współpracować z kolegami.",
    },
    {
        sala: 230,
        imie: "Monika",
        nazwisko: "Chałowska",
        przedmiot: ["J. Polski", "Antropologia Kulturowa"],
        opis: "Przychodzić na lekcje, kochać język polski, odnajdywać przyjemność w rozwijaniu się.",
    },
    {
        sala: 237,
        imie: "Dagmara",
        nazwisko: "Wicińska",
        przedmiot: ["J. Polski"],
        opis: "Nie bać się wyrażania własnej opinii, być otwartym na rozmowy, czytać teksty obowiązkowe, odnosić się z szacunkiem do wszystkich.",
    },
    {
        sala: 240,
        imie: "Michał",
        nazwisko: "Polak",
        przedmiot: ["PLSK", "PTST", "Uruchamianie i konfigurowanie sieci komutacyjnych", "Pracownia instalacji telekomunikacyjnych",
        ],
        opis: "Uczyć się, mieć szacunek.",
    },
];